import type { WeaponId } from "./WeaponDefs";

export type UpgradeKind = "weapon-unlock" | "weapon-upgrade" | "boost";

export interface UpgradeDef {
  id: string;
  kind: UpgradeKind;
  label: string;
  description: string;
  maxLevel: number;
  icon?: string;
  weapon?: WeaponId;
}

export const UPGRADE_DEFS: UpgradeDef[] = [
  {
    id: "unlock-magicOrb",
    kind: "weapon-unlock",
    label: "Magic Orb",
    description: "Summon a magic orb that orbits you and damages nearby foes.",
    maxLevel: 1,
    icon: "magic-orb",
    weapon: "magicOrb",
  },
  {
    id: "unlock-boomerang",
    kind: "weapon-unlock",
    label: "Kunai",
    description: "Hurl a magic kunai that pierces enemies and returns to you.",
    maxLevel: 1,
    icon: "boomerang",
    weapon: "boomerang",
  },
  {
    id: "unlock-arrow",
    kind: "weapon-unlock",
    label: "Arrow Volley",
    description: "Fire fast arrows that pierce through multiple enemies.",
    maxLevel: 1,
    icon: "weapon-arrow",
    weapon: "arrow",
  },
  {
    id: "unlock-bomb",
    kind: "weapon-unlock",
    label: "Bomb",
    description: "Lob an explosive that deals area damage.",
    maxLevel: 1,
    icon: "weapon-bomb",
    weapon: "bomb",
  },
  {
    id: "unlock-caltrop",
    kind: "weapon-unlock",
    label: "Caltrops",
    description: "Scatter spikes around you that damage enemies over time.",
    maxLevel: 1,
    icon: "weapon-caltrop",
    weapon: "caltrop",
  },
  {
    id: "unlock-samuraiSword",
    kind: "weapon-unlock",
    label: "Samurai Sword",
    description: "Slash an arc in front of you. Pair with Twin Sai to awaken it.",
    maxLevel: 1,
    icon: "weapon-katana",
    weapon: "samuraiSword",
  },
  {
    id: "unlock-fireTrail",
    kind: "weapon-unlock",
    label: "Fire Trail",
    description: "Leave a trail of scorched earth that burns enemies who walk on it.",
    maxLevel: 1,
    icon: "fire-trail",
    weapon: "fireTrail",
  },
  {
    id: "unlock-holyWater",
    kind: "weapon-unlock",
    label: "Holy Water",
    description: "Hurl a vial that shatters into a blessed pool of damage.",
    maxLevel: 1,
    icon: "holy-water",
    weapon: "holyWater",
  },

  {
    id: "holyBeam-damage",
    kind: "weapon-upgrade",
    label: "Radiant Beam",
    description: "+8 holy beam damage.",
    maxLevel: 5,
    icon: "holy-beam",
    weapon: "holyBeam",
  },
  {
    id: "holyBeam-cooldown",
    kind: "weapon-upgrade",
    label: "Faster Revelation",
    description: "-15% holy beam cooldown.",
    maxLevel: 4,
    icon: "holy-beam",
    weapon: "holyBeam",
  },
  {
    id: "holyBeam-count",
    kind: "weapon-upgrade",
    label: "Second Coming",
    description: "+1 holy beam per salvo.",
    maxLevel: 2,
    icon: "holy-beam",
    weapon: "holyBeam",
  },
  {
    id: "holyWater-damage",
    kind: "weapon-upgrade",
    label: "Sanctified",
    description: "+4 holy water damage.",
    maxLevel: 5,
    icon: "holy-water",
    weapon: "holyWater",
  },
  {
    id: "holyWater-count",
    kind: "weapon-upgrade",
    label: "Extra Vial",
    description: "+1 holy water thrown.",
    maxLevel: 3,
    icon: "holy-water",
    weapon: "holyWater",
  },

  {
    id: "shuriken-damage",
    kind: "weapon-upgrade",
    label: "Sharper Shuriken",
    description: "+6 shuriken damage.",
    maxLevel: 5,
    icon: "shuriken",
    weapon: "shuriken",
  },
  {
    id: "shuriken-cooldown",
    kind: "weapon-upgrade",
    label: "Quick Draw",
    description: "-15% shuriken cooldown.",
    maxLevel: 4,
    icon: "shuriken",
    weapon: "shuriken",
  },
  {
    id: "shuriken-count",
    kind: "weapon-upgrade",
    label: "Extra Shuriken",
    description: "+1 shuriken per volley.",
    maxLevel: 3,
    icon: "shuriken",
    weapon: "shuriken",
  },

  {
    id: "magicOrb-damage",
    kind: "weapon-upgrade",
    label: "Empowered Orb",
    description: "+4 magic orb damage.",
    maxLevel: 5,
    icon: "magic-orb",
    weapon: "magicOrb",
  },
  {
    id: "magicOrb-count",
    kind: "weapon-upgrade",
    label: "Orb Multiplier",
    description: "+1 orbiting magic orb.",
    maxLevel: 3,
    icon: "magic-orb",
    weapon: "magicOrb",
  },

  {
    id: "boomerang-damage",
    kind: "weapon-upgrade",
    label: "Heavy Kunai",
    description: "+8 kunai damage.",
    maxLevel: 5,
    icon: "boomerang",
    weapon: "boomerang",
  },
  {
    id: "boomerang-count",
    kind: "weapon-upgrade",
    label: "Double Kunai",
    description: "+1 kunai per throw.",
    maxLevel: 2,
    icon: "boomerang",
    weapon: "boomerang",
  },

  {
    id: "arrow-damage",
    kind: "weapon-upgrade",
    label: "Sharpened Arrows",
    description: "+6 arrow damage.",
    maxLevel: 5,
    icon: "weapon-arrow",
    weapon: "arrow",
  },
  {
    id: "arrow-count",
    kind: "weapon-upgrade",
    label: "Volley Expansion",
    description: "+1 arrow per volley.",
    maxLevel: 3,
    icon: "weapon-arrow",
    weapon: "arrow",
  },
  {
    id: "arrow-pierce",
    kind: "weapon-upgrade",
    label: "Piercing Tip",
    description: "+1 arrow pierce.",
    maxLevel: 3,
    icon: "weapon-arrow",
    weapon: "arrow",
  },

  {
    id: "bomb-damage",
    kind: "weapon-upgrade",
    label: "Potent Explosive",
    description: "+20 bomb damage.",
    maxLevel: 5,
    icon: "weapon-bomb",
    weapon: "bomb",
  },
  {
    id: "bomb-cooldown",
    kind: "weapon-upgrade",
    label: "Short Fuse",
    description: "-15% bomb cooldown.",
    maxLevel: 3,
    icon: "weapon-bomb",
    weapon: "bomb",
  },

  {
    id: "caltrop-damage",
    kind: "weapon-upgrade",
    label: "Barbed Spikes",
    description: "+4 caltrop damage.",
    maxLevel: 5,
    icon: "weapon-caltrop",
    weapon: "caltrop",
  },
  {
    id: "caltrop-count",
    kind: "weapon-upgrade",
    label: "More Caltrops",
    description: "+1 spike per scatter.",
    maxLevel: 3,
    icon: "weapon-caltrop",
    weapon: "caltrop",
  },

  {
    id: "samuraiSword-damage",
    kind: "weapon-upgrade",
    label: "Honed Edge",
    description: "+10 samurai sword damage.",
    maxLevel: 5,
    icon: "weapon-katana",
    weapon: "samuraiSword",
  },
  {
    id: "samuraiSword-cooldown",
    kind: "weapon-upgrade",
    label: "Iaido Stance",
    description: "-15% samurai sword cooldown.",
    maxLevel: 3,
    icon: "weapon-katana",
    weapon: "samuraiSword",
  },
  {
    id: "dualKatana-damage",
    kind: "weapon-upgrade",
    label: "Twin Edge",
    description: "+8 dual katana damage.",
    maxLevel: 5,
    icon: "weapon-katana",
    weapon: "dualKatana",
  },
  {
    id: "dualKatana-count",
    kind: "weapon-upgrade",
    label: "More Blades",
    description: "+1 orbiting katana.",
    maxLevel: 2,
    icon: "weapon-katana",
    weapon: "dualKatana",
  },
  {
    id: "fireTrail-damage",
    kind: "weapon-upgrade",
    label: "Hotter Flames",
    description: "+5 fire trail burn damage.",
    maxLevel: 5,
    icon: "fire-trail",
    weapon: "fireTrail",
  },
  {
    id: "fireTrail-area",
    kind: "weapon-upgrade",
    label: "Wider Blaze",
    description: "+20% fire trail area.",
    maxLevel: 3,
    icon: "fire-trail",
    weapon: "fireTrail",
  },

  {
    id: "unlock-frostbolt",
    kind: "weapon-unlock",
    label: "Frostbolt",
    description: "Fire an icy shard that slows whatever it hits.",
    maxLevel: 1,
    icon: "frostbolt",
    weapon: "frostbolt",
  },
  {
    id: "unlock-poisonCloud",
    kind: "weapon-unlock",
    label: "Poison Cloud",
    description: "Drop a lingering toxic cloud at your feet.",
    maxLevel: 1,
    icon: "poison-cloud",
    weapon: "poisonCloud",
  },
  {
    id: "unlock-crossbow",
    kind: "weapon-unlock",
    label: "Crossbow",
    description: "Slow heavy bolt that punches through two enemies.",
    maxLevel: 1,
    icon: "crossbow-bolt",
    weapon: "crossbow",
  },
  {
    id: "unlock-chainLightning",
    kind: "weapon-unlock",
    label: "Chain Lightning",
    description: "Arcs between up to four nearby enemies.",
    maxLevel: 1,
    icon: "chain-bolt",
    weapon: "chainLightning",
  },
  {
    id: "unlock-homingShuriken",
    kind: "weapon-unlock",
    label: "Homing Shuriken",
    description: "Cursed star that curves to its target — cannot miss.",
    maxLevel: 1,
    icon: "shuriken",
    weapon: "homingShuriken",
  },

  {
    id: "frostbolt-damage",
    kind: "weapon-upgrade",
    label: "Deeper Chill",
    description: "+6 frostbolt damage.",
    maxLevel: 5,
    icon: "frostbolt",
    weapon: "frostbolt",
  },
  {
    id: "frostbolt-cooldown",
    kind: "weapon-upgrade",
    label: "Flash Freeze",
    description: "-15% frostbolt cooldown.",
    maxLevel: 4,
    icon: "frostbolt",
    weapon: "frostbolt",
  },

  {
    id: "poisonCloud-damage",
    kind: "weapon-upgrade",
    label: "Lethal Toxin",
    description: "+3 poison tick damage.",
    maxLevel: 5,
    icon: "poison-cloud",
    weapon: "poisonCloud",
  },
  {
    id: "poisonCloud-count",
    kind: "weapon-upgrade",
    label: "Twin Cloud",
    description: "+1 poison cloud per drop.",
    maxLevel: 2,
    icon: "poison-cloud",
    weapon: "poisonCloud",
  },

  {
    id: "crossbow-damage",
    kind: "weapon-upgrade",
    label: "Armor-Piercing",
    description: "+18 crossbow damage.",
    maxLevel: 5,
    icon: "crossbow-bolt",
    weapon: "crossbow",
  },
  {
    id: "crossbow-cooldown",
    kind: "weapon-upgrade",
    label: "Quick Crank",
    description: "-15% crossbow cooldown.",
    maxLevel: 3,
    icon: "crossbow-bolt",
    weapon: "crossbow",
  },

  {
    id: "chainLightning-damage",
    kind: "weapon-upgrade",
    label: "Overvolt",
    description: "+6 chain lightning damage.",
    maxLevel: 5,
    icon: "chain-bolt",
    weapon: "chainLightning",
  },
  {
    id: "chainLightning-count",
    kind: "weapon-upgrade",
    label: "Longer Arc",
    description: "+1 chain jump.",
    maxLevel: 3,
    icon: "chain-bolt",
    weapon: "chainLightning",
  },

  {
    id: "homingShuriken-damage",
    kind: "weapon-upgrade",
    label: "Cursed Edge",
    description: "+8 homing shuriken damage.",
    maxLevel: 5,
    icon: "shuriken",
    weapon: "homingShuriken",
  },
  {
    id: "homingShuriken-count",
    kind: "weapon-upgrade",
    label: "Extra Star",
    description: "+1 homing shuriken per volley.",
    maxLevel: 2,
    icon: "shuriken",
    weapon: "homingShuriken",
  },

  {
    id: "laserPointer-damage",
    kind: "weapon-upgrade",
    label: "Brighter Beam",
    description: "+4 laser pointer damage.",
    maxLevel: 5,
    icon: "laser-dot",
    weapon: "laserPointer",
  },
  {
    id: "laserPointer-cooldown",
    kind: "weapon-upgrade",
    label: "Twitchier Paws",
    description: "-15% laser pointer cooldown.",
    maxLevel: 4,
    icon: "laser-dot",
    weapon: "laserPointer",
  },
  {
    id: "laserPointer-count",
    kind: "weapon-upgrade",
    label: "Split Beam",
    description: "+1 laser dot per click.",
    maxLevel: 2,
    icon: "laser-dot",
    weapon: "laserPointer",
  },

  {
    id: "krabbyPatty-damage",
    kind: "weapon-upgrade",
    label: "Secret Formula",
    description: "+6 krabby patty damage.",
    maxLevel: 5,
    icon: "weapon-krabby-patty",
    weapon: "krabbyPatty",
  },
  {
    id: "krabbyPatty-cooldown",
    kind: "weapon-upgrade",
    label: "Fry Cook Expertise",
    description: "-15% krabby patty cooldown.",
    maxLevel: 4,
    icon: "weapon-krabby-patty",
    weapon: "krabbyPatty",
  },
  {
    id: "krabbyPatty-count",
    kind: "weapon-upgrade",
    label: "Double Patty",
    description: "+1 patty per toss.",
    maxLevel: 2,
    icon: "weapon-krabby-patty",
    weapon: "krabbyPatty",
  },
  {
    id: "bestFriends-damage",
    kind: "weapon-upgrade",
    label: "F is for Friends",
    description: "+5 best friends damage.",
    maxLevel: 5,
    icon: "weapon-krabby-patty",
    weapon: "bestFriends",
  },
  {
    id: "bestFriends-count",
    kind: "weapon-upgrade",
    label: "More Best Friends",
    description: "+2 patties per volley.",
    maxLevel: 3,
    icon: "weapon-krabby-patty",
    weapon: "bestFriends",
  },

  {
    id: "boost-speed",
    kind: "boost",
    label: "Swift Feet",
    description: "+12% movement speed.",
    maxLevel: 5,
    icon: "gear-feather",
  },
  {
    id: "boost-maxHp",
    kind: "boost",
    label: "Iron Body",
    description: "+25 max HP and heal to full.",
    maxLevel: 5,
    icon: "gear-amulet",
  },
  {
    id: "boost-regen",
    kind: "boost",
    label: "Regeneration",
    description: "+0.6 HP / second.",
    maxLevel: 3,
    icon: "item-medipack",
  },
  {
    id: "boost-magnet",
    kind: "boost",
    label: "Gem Magnet",
    description: "+50% gem pickup radius.",
    maxLevel: 3,
    icon: "gear-bag",
  },
  {
    id: "boost-damage",
    kind: "boost",
    label: "Battle Rage",
    description: "+10% damage to all weapons.",
    maxLevel: 5,
    icon: "gear-hammer",
  },
  {
    id: "boost-cooldown",
    kind: "boost",
    label: "Focused Mind",
    description: "-8% cooldown on all weapons.",
    maxLevel: 4,
    icon: "gear-hourglass",
  },
];

export const UPGRADES_BY_ID: Record<string, UpgradeDef> = Object.fromEntries(
  UPGRADE_DEFS.map((u) => [u.id, u]),
);
