import type { WeaponId } from "./WeaponDefs";
import type { ActiveItemId } from "../types/GameTypes";

export type UpgradeKind = "weapon-unlock" | "weapon-upgrade" | "boost" | "active-item";

export interface UpgradeDef {
  id: string;
  kind: UpgradeKind;
  label: string;
  description: string;
  maxLevel: number;
  icon?: string;
  weapon?: WeaponId;
  activeItem?: ActiveItemId;
}

export const UPGRADE_DEFS: UpgradeDef[] = [
  {
    id: "unlock-magicOrb",
    kind: "weapon-unlock",
    label: "Magic Orb",
    description: "Summon a magic orb that orbits you and damages nearby foes.",
    maxLevel: 1,
    icon: "magic-orb",
    weapon: "magicOrb",
  },
  {
    id: "unlock-boomerang",
    kind: "weapon-unlock",
    label: "Kunai",
    description: "Hurl a magic kunai that pierces enemies and returns to you.",
    maxLevel: 1,
    icon: "boomerang",
    weapon: "boomerang",
  },
  {
    id: "unlock-arrow",
    kind: "weapon-unlock",
    label: "Arrow Volley",
    description: "Fire fast arrows that pierce through multiple enemies.",
    maxLevel: 1,
    icon: "weapon-arrow",
    weapon: "arrow",
  },
  {
    id: "unlock-bomb",
    kind: "weapon-unlock",
    label: "Bomb",
    description: "Lob an explosive that deals area damage.",
    maxLevel: 1,
    icon: "weapon-bomb",
    weapon: "bomb",
  },
  {
    id: "unlock-caltrop",
    kind: "weapon-unlock",
    label: "Caltrops",
    description: "Scatter spikes around you that damage enemies over time.",
    maxLevel: 1,
    icon: "weapon-caltrop",
    weapon: "caltrop",
  },
  {
    id: "unlock-samuraiSword",
    kind: "weapon-unlock",
    label: "Samurai Sword",
    description: "Slash an arc in front of you. Pair with Twin Sai to awaken it.",
    maxLevel: 1,
    icon: "weapon-katana",
    weapon: "samuraiSword",
  },
  {
    id: "unlock-fireTrail",
    kind: "weapon-unlock",
    label: "Fire Trail",
    description: "Leave a trail of scorched earth that burns enemies who walk on it.",
    maxLevel: 1,
    icon: "fire-trail",
    weapon: "fireTrail",
  },

  {
    id: "shuriken-damage",
    kind: "weapon-upgrade",
    label: "Sharper Shuriken",
    description: "+6 shuriken damage.",
    maxLevel: 5,
    icon: "shuriken",
    weapon: "shuriken",
  },
  {
    id: "shuriken-cooldown",
    kind: "weapon-upgrade",
    label: "Quick Draw",
    description: "-15% shuriken cooldown.",
    maxLevel: 4,
    icon: "shuriken",
    weapon: "shuriken",
  },
  {
    id: "shuriken-count",
    kind: "weapon-upgrade",
    label: "Extra Shuriken",
    description: "+1 shuriken per volley.",
    maxLevel: 3,
    icon: "shuriken",
    weapon: "shuriken",
  },

  {
    id: "magicOrb-damage",
    kind: "weapon-upgrade",
    label: "Empowered Orb",
    description: "+4 magic orb damage.",
    maxLevel: 5,
    icon: "magic-orb",
    weapon: "magicOrb",
  },
  {
    id: "magicOrb-count",
    kind: "weapon-upgrade",
    label: "Orb Multiplier",
    description: "+1 orbiting magic orb.",
    maxLevel: 3,
    icon: "magic-orb",
    weapon: "magicOrb",
  },

  {
    id: "boomerang-damage",
    kind: "weapon-upgrade",
    label: "Heavy Kunai",
    description: "+8 kunai damage.",
    maxLevel: 5,
    icon: "boomerang",
    weapon: "boomerang",
  },
  {
    id: "boomerang-count",
    kind: "weapon-upgrade",
    label: "Double Kunai",
    description: "+1 kunai per throw.",
    maxLevel: 2,
    icon: "boomerang",
    weapon: "boomerang",
  },

  {
    id: "arrow-damage",
    kind: "weapon-upgrade",
    label: "Sharpened Arrows",
    description: "+6 arrow damage.",
    maxLevel: 5,
    icon: "weapon-arrow",
    weapon: "arrow",
  },
  {
    id: "arrow-count",
    kind: "weapon-upgrade",
    label: "Volley Expansion",
    description: "+1 arrow per volley.",
    maxLevel: 3,
    icon: "weapon-arrow",
    weapon: "arrow",
  },
  {
    id: "arrow-pierce",
    kind: "weapon-upgrade",
    label: "Piercing Tip",
    description: "+1 arrow pierce.",
    maxLevel: 3,
    icon: "weapon-arrow",
    weapon: "arrow",
  },

  {
    id: "bomb-damage",
    kind: "weapon-upgrade",
    label: "Potent Explosive",
    description: "+20 bomb damage.",
    maxLevel: 5,
    icon: "weapon-bomb",
    weapon: "bomb",
  },
  {
    id: "bomb-cooldown",
    kind: "weapon-upgrade",
    label: "Short Fuse",
    description: "-15% bomb cooldown.",
    maxLevel: 3,
    icon: "weapon-bomb",
    weapon: "bomb",
  },

  {
    id: "caltrop-damage",
    kind: "weapon-upgrade",
    label: "Barbed Spikes",
    description: "+4 caltrop damage.",
    maxLevel: 5,
    icon: "weapon-caltrop",
    weapon: "caltrop",
  },
  {
    id: "caltrop-count",
    kind: "weapon-upgrade",
    label: "More Caltrops",
    description: "+1 spike per scatter.",
    maxLevel: 3,
    icon: "weapon-caltrop",
    weapon: "caltrop",
  },

  {
    id: "samuraiSword-damage",
    kind: "weapon-upgrade",
    label: "Honed Edge",
    description: "+10 samurai sword damage.",
    maxLevel: 5,
    icon: "weapon-katana",
    weapon: "samuraiSword",
  },
  {
    id: "samuraiSword-cooldown",
    kind: "weapon-upgrade",
    label: "Iaido Stance",
    description: "-15% samurai sword cooldown.",
    maxLevel: 3,
    icon: "weapon-katana",
    weapon: "samuraiSword",
  },
  {
    id: "dualKatana-damage",
    kind: "weapon-upgrade",
    label: "Twin Edge",
    description: "+8 dual katana damage.",
    maxLevel: 5,
    icon: "weapon-katana",
    weapon: "dualKatana",
  },
  {
    id: "dualKatana-count",
    kind: "weapon-upgrade",
    label: "More Blades",
    description: "+1 orbiting katana.",
    maxLevel: 2,
    icon: "weapon-katana",
    weapon: "dualKatana",
  },
  {
    id: "fireTrail-damage",
    kind: "weapon-upgrade",
    label: "Hotter Flames",
    description: "+5 fire trail burn damage.",
    maxLevel: 5,
    icon: "fire-trail",
    weapon: "fireTrail",
  },
  {
    id: "fireTrail-area",
    kind: "weapon-upgrade",
    label: "Wider Blaze",
    description: "+20% fire trail area.",
    maxLevel: 3,
    icon: "fire-trail",
    weapon: "fireTrail",
  },

  {
    id: "boost-speed",
    kind: "boost",
    label: "Swift Feet",
    description: "+12% movement speed.",
    maxLevel: 5,
    icon: "gear-feather",
  },
  {
    id: "boost-maxHp",
    kind: "boost",
    label: "Iron Body",
    description: "+25 max HP and heal to full.",
    maxLevel: 5,
    icon: "gear-amulet",
  },
  {
    id: "boost-regen",
    kind: "boost",
    label: "Regeneration",
    description: "+0.6 HP / second.",
    maxLevel: 3,
    icon: "item-medipack",
  },
  {
    id: "boost-magnet",
    kind: "boost",
    label: "Gem Magnet",
    description: "+50% gem pickup radius.",
    maxLevel: 3,
    icon: "gear-bag",
  },
  {
    id: "boost-damage",
    kind: "boost",
    label: "Battle Rage",
    description: "+10% damage to all weapons.",
    maxLevel: 5,
    icon: "gear-hammer",
  },
  {
    id: "boost-cooldown",
    kind: "boost",
    label: "Focused Mind",
    description: "-8% cooldown on all weapons.",
    maxLevel: 4,
    icon: "gear-hourglass",
  },
  {
    id: "unlock-redBull",
    kind: "active-item",
    label: "Red Bull",
    description: "[SPACE] 2.5s mega speed boost. 12s cooldown. Replaces current active.",
    maxLevel: 1,
    icon: "item-redbull",
    activeItem: "redBull",
  },
  {
    id: "unlock-novaBlast",
    kind: "active-item",
    label: "Nova Blast",
    description: "[SPACE] Massive explosion around you. 18s cooldown. Replaces current active.",
    maxLevel: 1,
    icon: "weapon-bomb",
    activeItem: "novaBlast",
  },
];

export const UPGRADES_BY_ID: Record<string, UpgradeDef> = Object.fromEntries(
  UPGRADE_DEFS.map((u) => [u.id, u]),
);
